name: Build

on:
  push:
  pull_request:
    branches: ["main"]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Use stable toolchain
        run: echo "RUSTUP_TOOLCHAIN=stable" >> "$GITHUB_ENV"

      - name: Fetch dependencies
        run: cargo fetch --locked

      - name: Build
        run: cargo build --verbose --frozen --release

      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: build
          path: target/release/bday
